# Generated by Django manually for device support and port/prefix range support
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '__first__'),
        ('netbox_acls', '0004_netbox_acls'),
    ]
    
    operations = [
        # 1. Удаляем поля source_device и destination_device
        migrations.RemoveField(
            model_name='aclstandardrule',
            name='source_device',
        ),
        migrations.RemoveField(
            model_name='aclextendedrule',
            name='source_device',
        ),
        migrations.RemoveField(
            model_name='aclextendedrule',
            name='destination_device',
        ),
        
        # 2. Меняем тип полей портов с ArrayField на CharField
        migrations.AlterField(
            model_name='aclextendedrule',
            name='source_ports',
            field=models.CharField(
                blank=True,
                help_text='Port numbers or ranges (e.g., 80, 443, 1000-2000, eq www, range 445 1050)',
                max_length=100,
                verbose_name='Source Ports'
            ),
        ),
        migrations.AlterField(
            model_name='aclextendedrule',
            name='destination_ports',
            field=models.CharField(
                blank=True,
                help_text='Port numbers or ranges (e.g., 80, 443, 1000-2000, eq www, range 445 1050)',
                max_length=100,
                verbose_name='Destination Ports'
            ),
        ),
        
        # 3. Меняем тип полей префиксов с ForeignKey на CharField
        migrations.AlterField(
            model_name='aclstandardrule',
            name='source_prefix',
            field=models.CharField(
                blank=True,
                help_text='IP prefix, network or host (e.g., 192.168.1.0/24, 192.168.1.0 255.255.255.0, host 10.1.1.1)',
                max_length=100,
                verbose_name='Source Prefix/Host'
            ),
        ),
        migrations.AlterField(
            model_name='aclextendedrule',
            name='source_prefix',
            field=models.CharField(
                blank=True,
                help_text='IP prefix, network or host (e.g., 192.168.1.0/24, 192.168.1.0 255.255.255.0, host 10.1.1.1)',
                max_length=100,
                verbose_name='Source Prefix/Host'
            ),
        ),
        migrations.AlterField(
            model_name='aclextendedrule',
            name='destination_prefix',
            field=models.CharField(
                blank=True,
                help_text='IP prefix, network or host (e.g., 192.168.1.0/24, 192.168.1.0 255.255.255.0, host 10.1.1.1)',
                max_length=100,
                verbose_name='Destination Prefix/Host'
            ),
        ),
    ]
