# Generated by Django manually for device support and port range support
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '__first__'),
        ('netbox_acls', '0004_netbox_acls'),
    ]

    operations = [
        # 1. Добавляем поля для устройств
        migrations.AddField(
            model_name='aclstandardrule',
            name='source_device',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='dcim.device',
                verbose_name='Source Device'
            ),
        ),
        migrations.AddField(
            model_name='aclextendedrule',
            name='source_device',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='dcim.device',
                verbose_name='Source Device'
            ),
        ),
        migrations.AddField(
            model_name='aclextendedrule',
            name='destination_device',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='dcim.device',
                verbose_name='Destination Device'
            ),
        ),
        
        # 2. Меняем тип полей портов с ArrayField на CharField
        migrations.AlterField(
            model_name='aclextendedrule',
            name='source_ports',
            field=models.CharField(
                blank=True,
                help_text='Port numbers or ranges (e.g., 80, 443, 1000-2000, eq www, range 445 1050)',
                max_length=100,
                verbose_name='Source Ports'
            ),
        ),
        migrations.AlterField(
            model_name='aclextendedrule',
            name='destination_ports',
            field=models.CharField(
                blank=True,
                help_text='Port numbers or ranges (e.g., 80, 443, 1000-2000, eq www, range 445 1050)',
                max_length=100,
                verbose_name='Destination Ports'
            ),
        ),
    ]
