# Generated by Django manually for device support
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '__first__'),
        ('netbox_acls', '0004_netbox_acls'),
    ]

    operations = [
        migrations.AddField(
            model_name='aclstandardrule',
            name='source_device',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='dcim.device',
                verbose_name='Source Device'
            ),
        ),
        migrations.AddField(
            model_name='aclextendedrule',
            name='source_device',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='dcim.device',
                verbose_name='Source Device'
            ),
        ),
        migrations.AddField(
            model_name='aclextendedrule',
            name='destination_device',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='dcim.device',
                verbose_name='Destination Device'
            ),
        ),
    ]
